function Morphology = Init_Morphology(Fly_Data)
    import Utils.Standard_Wing
    import Utils.Standard_Body
    import Utils.mass_and_inertia
    import Utils.Init_Wing_Shape

    % Init the Morphology structure with NaNs
    wing_struct = struct(...
        'Wing_Shape', struct(),...
        'area', NaN,...
        'volume', NaN,...
        'center_of_gravity', NaN*zeros(1,3),...
        'mass', NaN,...
        'inertia', NaN*zeros(3),...
        'chord_lengths', NaN*zeros(1,21),...
        'N', NaN,...
        'wing_length', NaN,...
        'delta_r', NaN,...
        'moment_of_area_2', NaN,...
        'moment_of_area_3', NaN,...
        'wing_plane_angle', NaN,...
        'chord_cut', NaN,...
        'span_cut', NaN);
    Morphology = struct(...
        "Wing_LH", wing_struct,...
        "Wing_RH", wing_struct,...
        "Body", struct( ...
            "Body_Shape", struct(),...
            "joint", NaN*zeros(1,3),...
            "volume",NaN,...
            "mass", NaN,...
            "center_of_gravity", NaN*zeros(1,3),...
            "inertia", NaN*zeros(3),...
            "body_angle", NaN),...
        "total", struct( ...
            "mass",NaN,...
            "weight", NaN,...
            "center_of_gravity", NaN*zeros(1,3),...
            "moment_of_area_2_ratio", NaN,...
            "moment_of_area_3_ratio", NaN));

    % Load default body
    [Morphology.Body.Body_shape, Morphology.Body.Joint] = Standard_Body(0);

    % Construct wings
    [~, ~, ~, ~, ~, ~, lhWingLength_Max, lhChordLength_Max,...
        rhWingLength_Max, rhChordLength_Max] ...
        = Standard_Wing(0, 0, 100, 100, 0, 0, 100, 100);

    [Wing_left_x_data, Wing_left_y_data, Wing_left_z_data,...
        Wing_right_x_data, Wing_right_y_data, Wing_right_z_data]...
        = Standard_Wing(lhWingLength_Max, lhChordLength_Max,...
        Fly_Data.Span_Cut_LH, Fly_Data.Chord_Cut_LH, rhWingLength_Max, ...
        rhChordLength_Max, Fly_Data.Span_Cut_RH, Fly_Data.Chord_Cut_RH);

    Morphology.Wing_LH.wing_shape = Init_Wing_Shape(...
        Wing_left_x_data,Wing_left_y_data,Wing_left_z_data);
    Morphology.Wing_RH.wing_shape = Init_Wing_Shape(...
        Wing_right_x_data,Wing_right_y_data,Wing_right_z_data);

    % Add mass and inertia
    Morphology = mass_and_inertia(...
        Morphology.Wing_LH.wing_shape,Morphology.Wing_RH.wing_shape,...
        Morphology.Body.Body_shape,Morphology);

    % legacy feature: CG is considered the joint for robotic flies
    Morphology.total.CG = Morphology.Body.Joint;

    % Extract info from Fly_Data
    Morphology.Body.Body_angle          = Fly_Data.Body_Angle;
    Morphology.Wing_LH.Wing_Plane_angle = Fly_Data.Wing_Plane_Angle_LH;
    Morphology.Wing_RH.Wing_Plane_angle = Fly_Data.Wing_Plane_Angle_RH;

end